### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by crichID** [tour-guide/tour-guide-web#4]
# Fairy Tale Audio Tours

**Description:**  

Personal self-guided audio tours on-demand!

Engaging the community to get involved and share their history and stories. We want to create an app that allows users to create their own tours and share them with the world. Members of the community can:

- create a profile
- take an audio tour at your own pace
- create a tour
- and save favorites

**User Story** 

As someone who loves to explore the world around me, I want a single resource where I can access high-quality tours that appeal to my personal interests and provide insider knowledge about the places I am visiting.

### Wireframe

Mock-up of the project: https://xd.adobe.com/view/2fa2e545-fc70-457c-7392-45f8e0a5eb41-5993/

### Project Requirements

- [x] Must use a Node and Express server
- [x] Must be backed by a MySQL database and an ORM (we will use Sequelize)
- [x] Must utilize both GET and POST routes for retrieving and adding new data
- [x] Must be deployed using Heroku (with data)
- [x] Must utilize at least one new third-party API (we will use Google Places and Firebase)
- [x] Must have a polished UI
- [x] Must use a CSS framework other than Bootstrap (we will use Materialize)
- [x] Must follow MVC paradigm
- [x] Must meet good quality coding standards (indentation, scoping, naming)
- [x] Must use Handlebars.js (we will use nunjucks.js)

### Task Breakdown

See Project board: https://github.com/tour-guide/tour-guide-web/projects/1
