### ISSUE TITLE
Presentation Day Checklist

### ISSUE THREAD

**Issue by crichID** [tour-guide/tour-guide-web#41]
@dropcat13 and @MandyTorrence my brain keeps going over the things that need to be finished up before tomorrow so I thought it might be best to create a checklist here to free up some mental space:

### DevOps

- [x] Get the heroku deployments in a happy place

### Page Designs are presentation ready

- [ ] logged out home (1/10 welcome and sign in or continue as guest)
- [ ] logged in home (4/10 after signup or sign in , show options to find stories or create a story)
- [x] signup (2/10 creating a new account)
- [x] stories (3/10 see all of the stories and select the one you want to view)
- [x] story (5/10 see the details for a specific story)
- [x] new (6/10 create a story)
- [x] login (7/10 logging in)
- [ ] profile public (9/10 viewing the user's profile)
- [x] profile private (10/10 user's view of their profile)

### Pages are functioning properly on heroku

- [ ] logged out vs. logged in home
- [x] signup
- [x] stories
- [x] story
- [x] new
- [x] login
- [ ] profile public
- [x] profile private

### Other

- [ ] The app doesn't fail very gracefully right now, need to add better handling for most common errors
- [x] I don't think we are actually using handlebars/nunjucks yet

### Tours in production!

- [x] Cynthia creates a tour
- [x] Mandy creates a tour
- [x] Cat creates a tour

**Comment by crichID** [comment]
I'm working on the profile public/private page now!

**Comment by crichID** [comment]
## Punch list 

- [ ] `/` is still redirecting to `/stories` need to make a logged out/logged in home
- [ ] If login fails, it takes you to the home page instead of giving you an error
- [ ] If sign up fails, it is throwing an error, even though it saves the account
- [ ] After story is submitted, go to the story page
- [ ] fix form select function in new file
- [ ] need an API/new route

**Comment by cynthiarich** [comment]
I moved all of the pending items here to the project board so closing out this issue!
